# Generated by Django 4.0 on 2022-01-04 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nft_id', models.IntegerField()),
                ('nft_id_str', models.TextField(default='1')),
                ('category', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='userp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='likeduserlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nftl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nft_user.nft')),
                ('userl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nft_user.userp')),
            ],
        ),
    ]
