# Generated by Django 4.0 on 2022-01-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='likeduserlist',
            name='nft_id_str',
            field=models.TextField(default='1'),
        ),
    ]
