# Generated by Django 4.0 on 2022-01-04 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nft_user', '0002_likeduserlist_nft_id_str'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likeduserlist',
            name='nft_id_str',
        ),
    ]
