# Generated by Django 4.0 on 2022-01-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft_user', '0003_remove_likeduserlist_nft_id_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='nft_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
