# Generated by Django 4.0 on 2022-01-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft_user', '0004_alter_nft_nft_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userp',
            name='nftlike',
            field=models.ManyToManyField(to='nft_user.nft'),
        ),
        migrations.DeleteModel(
            name='likeduserlist',
        ),
    ]
