# Generated by Django 4.0 on 2022-01-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft_user', '0005_userp_nftlike_delete_likeduserlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userp',
            name='nftlike',
        ),
        migrations.AddField(
            model_name='userp',
            name='nftlike',
            field=models.TextField(default='1'),
        ),
    ]
